#! /usr/bin/env bash
# vim: noai:ts=4:sw=4

# DESCRIPTION
#   Generates a template for a file based on its extension.
#
# USAGE
#   gen-template out.ext

CURR_PATH="$(pwd)"
SCRIPT_PATH="$(dirname "$(readlink -f "$0")")"
TEMPLATE_PATH="$(dirname "$SCRIPT_PATH")/templates"

get_file_extension() {
    file=$1
    ext=`echo "$file" | cut -d '.' -f2`   
    echo $ext
}

gen_file() {
    file=$1
    ext=$(get_file_extension $file)
    template="t.$ext"
    cat "$TEMPLATE_PATH/$template" > "$CURR_PATH/$file"
}

if [ ! -e $1 ]; then
    gen_file $1
fi
$EDITOR "$CURR_PATH/$1"
